### ISSUE TITLE
add a "resume from" feature

### ISSUE THREAD

**Issue by LingKuja** [zaps166/QMPlay2#508] opened 2022-05-26 18:26 UTC
Hello. I would like to ask you if it was possible to have a feature like in vlc, where it asks you if you want to resume a media from where you last left it. it would be great for resuming podcasts or long videos.
It would also be very nice to have a "jump to" feature on the player, as it would really improve when skipping to a certain timestamp in long videos.

so far i'm loving it. it reminds me of foobar2000

**Comment by zaps166** [comment] 2022-05-27 14:16
Hey, QMPlay2 has option: "Playback settings->Remember playback position". It restores playback of current file after restart.

**Comment by LingKuja** [comment] 2022-05-27 14:31
I didn't find it in time then, sorry. But I can't get it to work, for some reason. Because even when ticked on, if I close and reopen QMPlay2 it won't restart from where I left it. this goes for both streams and local files.

**Comment by zaps166** [comment] 2022-05-27 16:18
Did you press "Apply" button?

**Comment by LingKuja** [comment] 2022-05-27 16:30
> Did you press "Apply" button?

Yes.

I don't know if this is any useful, but my OS is Windows 10, version 21H2 (build 19044.1645)

**Comment by zaps166** [comment] 2022-06-01 09:29
Is it what you need or is it a duplicate of #156?

**Closed** 2022-06-01 11:00 UTC
