### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by podtor** [zaps166/QMPlay2#359] opened 2020-10-03 20:57 UTC
During full screen don't block turn off the display.

**Comment by Digitalone1** [comment] 2020-10-04 19:55
Maybe a duplicate of #344

**Comment by podtor** [comment] 2020-10-04 20:08
Similar but this problem regard Windows

**Comment by zaps166** [comment] 2020-10-05 23:21
I'll check it

**Comment by zaps166** [comment] 2021-03-16 20:11
Works properly on Windows 10, hmm. On full screen audio and video playback blocks turn off the display.

**Comment by zaps166** [comment] 2022-03-18 23:36
I can't reproduce on 3 computers with Windows 10 - QMPlay2 properly inhibits screensaver. (fullscreen with stopped playback doesn't inhibit!)

**Closed by zaps166** 2022-03-18 23:36 UTC
Labels: need more info
