### ISSUE TITLE
OSD Notifications Not Work on Certain Conditions

### ISSUE THREAD

**Issue by zo-shin** [zaps166/QMPlay2#329] opened 2020-05-07 14:13 UTC
Hide the tray icon. When the player is idle, perform some notification operations like changing volume, the OSD notifications don’t work. When audio files are played, they don’t work, either.

**Comment by zaps166** [comment] 2020-05-10 22:03
I don't understand. Could you upload a GIF?

OSD works only on video content.

**Comment by zo-shin** [comment] 2020-05-11 00:06
Can it be useful to make it work on audio files?

**Comment by notramo** [comment] 2020-05-16 08:25
Duplicate of #176

**Closed** 2024-12-11 18:18 UTC
Labels: duplicate
