### ISSUE TITLE
Blank video on wayland and vulkan

### ISSUE THREAD

**Issue by patlefort** [zaps166/QMPlay2#484] opened 2022-02-08 05:47 UTC
Using the vulkan renderer, if I launch qmplay2 with wayland `QT_QPA_PLATFORM=wayland QMPlay2`, the video will be blank. In X mode `QT_QPA_PLATFORM=xcb QMPlay2`, it will work fine. Tested on 2 machines, one with AMD (both integrated and discrete) and one with nvidia proprietary drivers. Regardless of which decoder I use.

This is on Arch Linux, all up to date of course.

**Comment by zaps166** [comment] 2022-02-08 12:56
I'm not familiar with Wayland, but It works for me, Vulkan + VA-API onManjaro Linux (Radeon, Weston).
Launch command: `QMPlay2 -platform wayland`.

**Comment by patlefort** [comment] 2022-02-08 13:36
I tested on Weston and it works. Can you test on KDE or Gnome with wayland instead of the reference implementation of wayland? Maybe there's a problem with their implementation of wayland?

**Comment by zaps166** [comment] 2022-02-08 13:47
KDE: Black screen.

**Comment by DarkWav** [comment] 2022-02-08 14:10
So, I did some testing across multiple configs:
Arch + KDE + Wayland + NVIDIA = **black video**
Arch + GNOME + Wayland + NVIDIA = **works**
openSUSE + KDE + Wayland + NVIDIA = **Vulkan renderer completely refuses to enable with error:**
```
Vulkan :: Discarding "NVIDIA GeForce RTX 2070 SUPER", because:
   - Present is not supported
Vulkan :: Discarding "llvmpipe (LLVM 13.0.0, 256 bits)", because:
   - Not a GPU
[08 Feb. 2022 15:05:55.807] Vulkan is unable to work with QMPlay2 on this platform: No compatible devices found: ErrorInitializationFailed
```
openSUSE + GNOME + Wayland + NVIDIA = **works**
openSUSE + KDE + Wayland + Intel Mesa = **black video**
openSUSE + GNOME + Wayland + Intel Mesa = **works**

Maybe something is wrong in KDE's wayland implementation?

**Comment by zaps166** [comment] 2022-02-08 14:17
It's good to test with non-Qt native Wayland app (SDL2).

**Comment by zaps166** [comment] 2022-02-08 14:21
I can confirm, SDL2 Wayland Vulkan app is working on KDE.

**Comment by zaps166** [comment] 2022-02-08 14:43
The problem is with docking a `QWindow` in a `QWidget` - looks like Qt and/or KWin have problems with this, but this is necessary for Vulkan.

You can get the same bug on OpenGL when you `return false` in `QMPlay2CoreClass::isGlOnWindowForced()` function and disable using OpenGL on entire window.

It's impossible to fix in QMPlay2 by me for now. It should be fixed in Qt Wayland plugin and/or in KWin. It works on Weston, but doesn't work well. I didn't test GNOME.

**Comment by patlefort** [comment] 2022-02-09 17:58
Should a bug be reported to QT or KWin? I don't know either enough to provide information.

**Comment by zaps166** [comment] 2022-02-10 10:12
I don't know. Maybe KWin, because it works on GNOME and Weston.

It's not related to Vulkan, but to embedding window inside a window.

**Comment by zaps166** [comment] 2022-02-21 18:00
kwin 5.24.1 - still the same issue. I don't know how to "fix" on my side, this works even on Android...

**Comment by zaps166** [comment] 2022-02-21 23:56
Gnome (Mutter 41) - also doesn't work. Are you sure you run QMPlay2 on wayland plugin, not xwayland?

**Comment by zaps166** [comment] 2022-02-23 00:51
I've made a workaround, it should now work. Remaining issues:
- bottom panel with seek slider is invisible on full screen,
- toggling full screen or compact mode or displaying left panel can cause a crash,
- mouse cursor might not disappear automatically - need to move cursor to different position,
- resizing widgets is aborted when mouse is over Vulkan video area,

**Closed by zaps166** 2022-02-23 00:51 UTC
Labels: out of scope
