### ISSUE TITLE
Youtube search does not give results

### ISSUE THREAD

**Issue by MariasStory** [zaps166/QMPlay2#411] opened 2021-04-08 07:40 UTC
It seems that youtube search does not give results.
Please check.

**Comment by zaps166** [comment] 2021-04-08 11:25
Should be already fixed on master (#406).

**Closed by zaps166** 2021-04-08 11:25 UTC

**Comment by DarkWav** [comment] 2021-04-08 18:36
As @zaps166 said, the issue is well-known and has already been fixed on master.
If you are running Arch Linux or some derivative make sure to use the `qmplay2-git` package from the AUR as the normal `qmplay2` package currently does not contain the fix.
If you use openSUSE Tumbleweed update to at least version `21.03.09-4.1`
For all other operating systems you need to build the latest git master from source, here's a guide how to do that:
https://github.com/zaps166/QMPlay2/blob/master/README.md#installation-from-sources

**Comment by zaps166** [comment] 2021-04-09 11:03
I should rewrite it to script to avoid similar issues :smile:
