### ISSUE TITLE
Audio CD Menu add crash QMPlay2

### ISSUE THREAD

**Issue by KetjowTrzy** [zaps166/QMPlay2#489] opened 2022-03-08 07:54 UTC
I have a problem with playing Audio CDs. When You try to add and play Audio CD from right click menu into the playlist whole QMPlay2 crash. Only work solution is to add Audio CD as a folder from right click menu. I use Windows 10 with external USB DVD Burner (LG HL-DT-ST DVDRAM GP10NW20). Please fix it.

**Comment by zaps166** [comment] 2022-03-09 20:32
I reproduced the crash, it looks like problem with compilation or linker (not source code), I'll try to fix it into next release!

**Comment by KetjowTrzy** [comment] 2022-03-10 08:14
Thank You.

**Comment by zaps166** [comment] 2022-03-19 22:03
Should be fixed in 22.03.19!

**Closed by zaps166** 2022-03-19 22:03 UTC
Labels: bug
