### ISSUE TITLE
"Remember playback position" between sessions, not working

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#596] opened 2023-03-20 19:52 UTC
I have enabled and accepted "Resume video from last position" (well, I'm translating, maybe not exactly that sentence in English interface) but after trying a lot of times, it doesn't work for me. I thought issue was related to that my videos are in a remote NAS, but in fact, doesn't work even with local files, I don't know why. Option is enabled since I enabled it months ago, and never worked (for me).

Could I give more info about issue?

![imagen](https://user-images.githubusercontent.com/13048959/226450061-ebe97f53-6814-4138-bc1f-797d0ab636a0.png)

**Comment by RafaelLinux** [comment] 2023-03-20 20:33
"Remember playback position" ("Recordar la posición de reproducción") is exactly what I have enabled, as you can see in attached photo :(
I saw that closed issue, but as I wrote here, I enabled it months ago (and even tried to disable/enable again) but nothing changed. As you can see, when I open QMP2, it's enabled.

**Comment by zaps166** [comment] 2023-03-22 22:54
How did you test this function?

**Comment by RafaelLinux** [comment] 2023-03-23 01:57
1. I begin to play a video and at some point, close QMP2
2. I click again in video file (from Dolphin)
3. As QMP2 is my default media player, it opens again same video, but start from beginning (any kind of video file)

**Comment by RafaelLinux** [comment] 2023-03-23 21:30
I think it's a distinct concept about "Remember". In SMPlayer (that I used before discover fantastic QMP2) and in VLC, if user enables "Remember position" it works between sessions for a specific filename in specific path (as when you use KODI or Amazon Prime and they remember last position).

**Comment by zaps166** [comment] 2023-03-24 21:47
I see, duplicate of #156

**Closed by zaps166** 2023-03-24 21:47 UTC
Labels: duplicate
