### ISSUE TITLE
YouTube search completely broken.

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#365] opened 2020-10-26 15:50 UTC
Since around 3-4 days YouTube search seems to be broken completely.
Maybe it has to do with this:
https://git.rip/lucifer/youtube-dl/-/commit/416da574ec0df3388f652e44f7fe71b1e3a4701f
_(It's a git.rip link because the *******s that call themselves "RIAA" filed a hillarious DMCA takedown request against youtube-dl)_
Other things like watching videos from direct links still works fine though.
The general download of youtube-dl is very inconsistent, it seems to work on chrome but fail on Firefox and QMPlay2's built-in download function.

**Comment by thubble** [comment] 2020-10-31 18:29
This looks like a duplicate of #358. I added a comment with a patch which should fix it.

**Closed** 2020-11-04 12:11 UTC
Labels: duplicate
