### ISSUE TITLE
[Feature Request] qmplay2 radio stations

### ISSUE THREAD

**Issue by penguin31** [zaps166/QMPlay2#106] opened 2017-05-09 06:48 UTC
@zaps166  Great qmplay2!!!
The lyrics shows for songs in radio stations or played songs (I asked for this improvement some times ago).
Just a small issue: The lyrics windows blinks continuously  (maybe refreshing ! ).Can be stable?
I have tried to find where the database e radio stations was saved , but i did not.I added manually some favorite radio stations.
Will be great if you include a windows/table(that reads database),when one can write station radio name; URL of station name,icon for radio station (if possible) or to chose from your icon gallery.
Right Click in the station name should give the possibility not only Remove The radio Station but also Edit Radio Station.
Lately i found that station list is saved under ......\QMPlay2\settings in Radio.ini file ( that populates only when you add new stations to qmplay2). - This is when qmplay2 run an Windows OS.
Suppose that similar will be for qmplay2 run in a Linux OS(somewhere under /qmplay2 or inside  user/.config folders) but I did not found nowhere.
@zaps166 ... where qmplay2 saves station list in a LinusOS?

**Comment by zaps166** [comment] 2017-05-09 08:06
[Radio browser](https://www.google.pl/url?q=http://www.radio-browser.info/&sa=U&ved=0ahUKEwj4qbjzrOLTAhXLJ1AKHT_2D7EQFggLMAA&usg=AFQjCNGZyrSzqf-o-5FRVsgH7DvpbffPXg) is under construction :)

**Comment by zaps166** [comment] 2017-05-10 15:29
@penguin31

> where qmplay2 saves station list in a LinusOS?

Settings on Linux are in home directory, `~/.qmplay2` or `${HOME}/.qmplay2`

> The lyrics windows blinks continuously (maybe refreshing ! ).Can be stable?

Please tell me steps to reproduce (also with song title and artist) - it doesn't happen for me.

**Comment by zaps166** [comment] 2017-05-14 15:39
Radio module has been improved, closing because of d3cf1ce3c61242150c9185a1c55cc63957aabb2b

**Closed by zaps166** 2017-05-14 15:39 UTC
Labels: enhancement

**Comment by zaps166** [comment] 2017-05-14 16:06
> The lyrics windows blinks continuously (maybe refreshing ! ).

Fixed: 06b625a6ef7bd97ba11c6b5fc01e21cca5be66f4
