### ISSUE TITLE
qmplay2 deletes Radio.ini

### ISSUE THREAD

**Issue by penguin31** [zaps166/QMPlay2#112] opened 2017-07-20 05:25 UTC
Randomly qmplay2 deletes Radio.ini file. I cant the frequency but simply the list of radio stations became blank because qmplay2 recreates a new Radio.ini.

**Comment by zaps166** [comment] 2017-07-20 06:28
I'll check this

**Comment by penguin31** [comment] 2017-07-20 07:01
I just found that has deleted in my work laptop but also happens many times in my home machine / windows and Linux also ! I have noticed this from the first install of last version.When I installed over the previous version as portable and I get trouble.I noticed that last version is not portable anymore (when one chose to install it on portable mode).You use Windows ...//user//documents and settings to save qmplay2 settings. Please check installer mode / portable and lets/respects user defined directory for install because installer do not copy files in the directory written in installer's path but to another one ; where installer starts ( I think).
Please upgrade your code to have possibility to make an silent upgrade from Help/Updates/Download Update or Upgrade with previous settings and backup in a zip file the previous installation inside the directory.I remember that Aimp.ru has used this method of upgrade.I am stuck with old gold version of AIMP v2.61.583 that pumps sound to the maximum. 
Suggestion. Can you add possibility to play stream files of TV ? Lets say one has downloaded a list file from internet and he use qmplay2 or VLC to see TV instead of KODI?

All the best . Have a great day ! 

    On Thursday, July 20, 2017 8:28 AM, Błażej Szczygieł <notifications@github.com> wrote:
 

 I'll check this—

**Comment by zaps166** [comment] 2017-07-20 18:53
> I have tried a list of streamed TV but qmplay2 did not play it.

Not related to this issue, but could you give me this list? Maybe In separate issue.

> Please upgrade your code to make an silent upgrade from Help/Updates/Download Update or Upgrade with previous settings and backup in a zip file the previous installation inside the directory.I remember that Aimp.ru has used this method of upgrade.

You can disable auto updates and do it manually. Backup of previous installation is not necessary, you can always disable updates and install older version (available on github).

>  All the best . Have a great day !

Thanks 😄

**Comment by zaps166** [comment] 2017-07-20 18:56
Ok, I caught the bug - sorry for this - I haven't tested it well (personally I rarely use "My radio stations"): radio list is read from settings only when Radio tab is visible. When it is not visible it doesn't read it and on close it saves empty list.

**Closed** 2017-07-20 19:04 UTC
Labels: bug

**Comment by zaps166** [comment] 2017-07-20 19:21
> You use Windows ...//user//documents and settings to save qmplay2 settings. Please check installer mode / portable and lets/respects user's defined directory for install because installer do not copy files in the directory in installer's path but to another one ; where installer starts ( I think).

Which settings exactly (I can't reproduce)? If you have a problem with it, create a separate issue :)

---

Installer in portable mode unpacks QMPlay2 to chosen directory (e.g. Desktop) and that's all. Installer uses `%temp%` directory for runtime. Portable QMPlay2 means that in the same dir as `QMPlay2.exe` file is another (empty) file `portable` (w/o file extension). Then QMPlay2 creates settings in the same directory as exe file in `settings` subdir and also doesn't ask for file associations. Installer in portable mode creates the `portable` file.

**Comment by penguin31** [comment] 2017-07-21 07:37
Thanks for your work.

Just I rechecked issue of installer.Sorry my mistake.
If one want to chose install in portable mode - first click portable and after that-change the path to the desired path, else if you fixed the installing path and click portable,installer will reset your path to %user%//desktop/qmplay2.

Solved. 

I still persist :-).Please ad to Qmplay2 an simple editor that can read and write Radio.ini and/or Playlist.pls file.

Have a great day !

**Comment by zaps166** [comment] 2017-07-21 15:57
> I still persist :-).Please ad to Qmplay2 an simple editor that can read and write Radio.ini and/or Playlist.pls file.

Hmm, a button to run e.g. Notepad++ ? :smile:
